oxc-project/oxc-project.github.io

- docs/index.md
I just fixed some links (the files is formatted by Prettier).
I will merge this PR immediately.
> fix: fix links

- .vitepress/config.mts
- .vitepress/sidebar.blog.json
- cli/commands/create-blog-post.mts
- cli/index.mts
- package.json
- pnpm-lock.yaml
I added CLI to automate blog post generation and sidebar synchronization.
From now on, you don't have to modify sidebar configuration manually every time you create blog post.
**Usage Details**
If you run:
```bash
pnpm run create-blog-post 2023-12-01 "Blog Title"
```
the result is:
- `/src/blog/2023-12-01-blog-title.md` is created
- `/.vitepress/sidebar.blog.json` is updated and the new blog post is shown in sidebar as first item
If you run:
```bash
pnpm run create-blog-post 2023-12-01 "Blog Title" --slug="custom-slug" --author=boshen
```
the result is:
- `/src/blog/2023-12-01-custom-slug.md` is created, where `boshen` is set in `authors` array of frontmatter
- `/.vitepress/sidebar.blog.json` is updated and the new blog post is shown in sidebar as first item
---
Let me merge this PR …
> feat: add cli for automation

- .github/workflows/ci-pr-label.yml
I found that `CI (PR Label)` workflow doesn't work if the PR comes from folk repositories.
I just fixed it with a notice.
@Boshen @Ubugeeei 
Let me assign you as reviewers to notify this change.
> fix(core): fix GitHub workflow event to listen

- src/docs/learn/parser_in_rust/ast.md
- src/docs/learn/parser_in_rust/errors.md
- src/ja/docs/learn/parser_in_rust/ast.md
- src/ja/docs/learn/parser_in_rust/errors.md
- src/zh/docs/learn/parser_in_rust/ast.md
- src/zh/docs/learn/parser_in_rust/errors.md
Looks like `vitepress` doesn't support `note`
> docs(core): update `note` to `info`

- .vitepress/config/en.ts
- .vitepress/config/ja.ts
- .vitepress/config/zh.ts
The playground link should move the top nav better. This is a link that is clicked more often.
The vast majority of websites do this, for example
* https://vuejs.org/
* https://biomejs.dev/
* https://swc.rs/
> docs: move playground to top nav

- src/docs/guide/usage/linter.md
The linter usage docs mention "eslint-plugin-oxc," but the package is actually called "eslint-plugin-oxlint."
> docs: fix typo

- src/docs/guide/usage/linter.md
I noticed that `oxlint` dropped support for `--codeowners-file` and `--codeowners`. 
This PR updates the "Help details" section of the linter page to use up-to-date information
> Update the 'Help details' section

- src/docs/guide/usage/linter.md
Hi , in the `actions/checkout` documentation it recommends using version 4.
You can see this -> [https://github.com/actions/checkout](https://github.com/actions/checkout)
> [FIX] Actions checkout to v4

- .vitepress/config/index.ts
- .vitepress/config/rss.ts
- package.json
- pnpm-lock.yaml
Fixes #104
- Only implements RSS & Atom feeds for the English blog.
- It is only available via `<link>` tags in the header (RSS autodiscovery), and isn't linked to anywhere on the website.
- It will throw an error if it cannot find a date for a blog post, which is a breaking change from what previous date-handling code for this website does.
- I don't know what decisions you want to make (what title to use for the feeds, what path the feeds should be located at, etc.), so this PR is to get the ball rolling.
- I'm likely not going to implement feeds for the other languages, as I'm not entirely sure how those should be handled.
> feat: implement RSS & Atom feeds for the English-language blog

- .vitepress/config/index.ts
`head` in `sharedConfig` is overridden by `rssConfig`, cause website has no favicon
> fix: head configs overridden by rss config

- .vitepress/config/shared.ts
- package.json
- pnpm-lock.yaml
- src/index.md
<details>
<summary>TL;DR: Fixes this unintended horizontal scroll bar appearance.</summary>
To make sponsor image responsive, we need to set `svg`'s container size as `width: 100%`.
And also `svg` element should have `viewBox` attribute to render inner content properly.
But `vite-svg-loader`(rather their deep dependency `svgo`) removes `viewBox` property by default...
To cope with it, there are 3 ways:
1. Override default config like: https://github.com/jpkleemans/vite-svg-loader/pull/120
2. Add `viewBox="0 0 800 691"` attribute manually
3. Do not rely on loaders
I chose 3 for simplicity and faster build time.
</details>
> Make sponsors section responsive

- .eslintignore
- package.json
- pnpm-lock.yaml
- bump oxlint to v0.7.2
- lint components and theme in .vitepress
> chore: lint files in .vitepress

- src/docs/contribute/performance.md
Improves documentation around how to use the samply profiler, with suggestions on how to get more data and make it easier to analyze. Also added information on how to compile with the newly added `release-with-debug` profile so that you don't need to manually edit Cargo.toml.
> Add docs on samply and release-with-debug profile

- src/docs/learn/ecmascript/spec.md
- src/docs/learn/parser_in_rust/errors.md
- src/docs/learn/parser_in_rust/lexer.md
Hey,
I think some code snippets were expected to highlight some lines but they were not performed. This PR aims to fix that.
Current behavior:
With changes from this PR:
> fix: highlighted lines in code snippets

- src/docs/learn/parser_in_rust/errors.md
Hey!
By checking the error docs, I realized that the enum variant for `SyntaxError::UnexpectedToken` had a typo in one of the snippets. This PR fixes it :)
> Fix typo in error snippet example

- src/docs/learn/parser_in_rust/lexer.md
Hey,
The lexer doc include links to rust source code for explanation but the `len()` code snippet shows the right link but wrong code. This PR fixes it.
> fix: len() code snippet in lexer doc

- src/docs/contribute/profiling.md
Adds some more detailed instructions on how to measure CPU Counters like L1 cache misses with Xcode.
> Add info on profiling L1 cache

- src/docs/contribute/linter/adding-rules.md
current doc is
after appended missing colons
> fix: `code-group`s lack of ending colons

- src/docs/contribute/vscode.md
The top-level `pnpm build` will only build the `napi/*` packages, but the `editors/vscode` package needs to be built in order for the `editors/vscode/oxc_language_server.vsix` file referenced in the next steps to be generated. I'm not actually sure if the `napi/*` packages are even required to be built, so maybe step 2 could be removed as well.
> Add step to build vscode lib in contributing doc

- .vitepress/config/en.ts
In the header, the `Resources > Blog` link currently points to [Oxc Transformer Alpha](https://oxc.rs/blog/2024-09-29-transformer-alpha.html).
However, it should link to the Oxlint v0.10 Migration Guide, as the latter is the newer resource.
> chore(blog): update blog link in the header component

- src/docs/contribute/linter/adding-rules.md
Match the content of the "Rule Generation" section with the behaviour of the `rulegen`.
> docs(linter): update "Rule Generation" section

- src/docs/guide/usage/linter.md
can be merged before releasing the next version 🥳
> docs(linter): inform about oxlint-migrate

- src/docs/guide/projects.md
Hey API uses Oxlint to lint the platform code (we should migrate ESLint in the public monorepo at some point)
> Add Hey API to projects using oxc

- .vitepress/config/en.ts
- src/docs/guide/usage/linter/config-file-reference.md
- src/docs/guide/usage/linter/config.md
- Towards https://github.com/oxc-project/oxc/issues/9529
- closes #8879 https://github.com/oxc-project/oxc/issues/8879
Adds a new guide on how to generally configure oxlint in the configuration, inline comments, and command-line. This serves as an overview to link to other pages that we can build upon for future PRs. I have moved the automatically generated config file reference to be its own page now.
> Add new guide on configuring oxlint

- src/docs/guide/usage/linter/plugins.md
- part of https://github.com/oxc-project/oxc/issues/9529
Updates the documentation for plugins to be accurate.
- Changes the CLI docs from `--no-<plugin>-plugin` to `--disable-<plugin>-plugin`
- Makes it more clear what the name of each plugin is
- Combines multiple ESLint plugins into one row (e.g., both `react` and `react-hooks` part of the `react` plugin)
- Adds docs on how to enable/disable plugins in the config files
> Update plugins docs

- src/docs/contribute/development.md
The filename of the snapshots is too long 🤣 on Windows OS.
> docs: update the bash script example about cloning the repo

- src/docs/guide/projects.md
[Elide](https://elide.dev) shipped its beta recently, which uses oxc's parser to strip TypeScript types. This PR adds it to the projects page :)
> Add Elide to `projects.md`

- src/docs/contribute/development.md
CMake now seems to be required in order to run e.g. `cargo clippy`. Add installation instructions to development setup guide.
> docs(development): CMake installation instructions

- .vitepress/config/inlined-scripts/banner.js
- .vitepress/config/shared.ts
- .vitepress/theme/components/Banner.vue
Ported some changes from https://github.com/vitejs/vite/pull/20419 to reduce the layout shift caused by the banner
[layoutshifts.webm](https://github.com/user-attachments/assets/e67f09cb-6008-4950-b795-9d9472856ae8)
> feat: reduce layout shift caused by banner

- src/docs/guide/usage/linter/config.md
When I first read through the docs "chronologically", it really confused me to reach the "Plugins" docs and see the list of available plugins with their "default" check marks, because the React plugin didn't have one. The comment right above my change says literally that all those enabled plugins in this example are "enabled by default", which is wrong. I am by no means a Rust expert, but I am pretty sure that this line here defines the default-enabled plugins to be OXC, Unicorn and TypeScript: https://github.com/oxc-project/oxc/blob/42de3d14da0a1c4f1a80c9e692627e928d556389/crates/oxc_linter/src/config/plugins.rs#L61, which means that the "Plugins" docs' table is correct, and this example config's comment here is not.
An alternative change would be to change the comment (instead of the …
> Clarified misleading example in "Configuring plugins" section

- src/docs/learn/architecture/test.md
Update section on memory safety and Miri.
It was a bit out of date - we now use static compile-time checks to prevent memory leaks, rather than leaning on Miri. Miri is used primarily to ensure the soundness of `unsafe` code.
> docs: update learn section on memory safety

- .husky/pre-commit
https://pnpm.io/cli/exec
I don't have `npm` installed, which results in 
```
/usr/bin/npx-default: No such file or directory
husky - pre-commit script failed (code 255)
```
> Use pnpm instead of npm in pre-commit check

- src/docs/learn/parser_in_rust/lexer.md
If length is 1, then function returns `Kind::Identifier`
> fix comment in lexer.md

- src/docs/guide/usage/linter/generated-cli.md
Closes [issue 13793](https://github.com/oxc-project/oxc/issues/13793#issuecomment-3305019352).
Added a blockquote to clarify that .gitignore is only respected in git repositories. 
Followed [plugins.md](https://github.com/oxc-project/oxc-project.github.io/blob/main/src/docs/guide/usage/linter/plugins.md?plain=1#L45-L46) for formatting.
> feat: specify that .gitignore is only respected in git repositories

- src/docs/guide/usage/linter.md
- src/index.md
https://oxc.rs/docs/guide/usage/linter/rules.html
> The progress of all rule implementations is tracked [here](https://github.com/oxc-project/oxc/issues/481).
> - Total number of rules: 602
> -  Rules turned on by default: 103
> docs(linter): supports +600 rules
