oxc-project/oxc-project.github.io

.vitepress/config.mts
=> fix: social link (github)

README.md
In line with the transition to VitePress, I corrected the commands that were not accurate, 
and I've also omitted the parts that overlap with the explanation of VitePress itself, replacing them with a link to VitePress. 
I'm referencing the README of the [vuejs/docs](https://github.com/vuejs/docs).
=> update: readme for contributing

.vitepress/config.mts, docs/index.md
- Fix `features` config in Home page
- Remove unused config
- Add footer
=> fix: fix home page contents

.vitepress/config.mts
=> remove dead config

.vitepress/theme/constants/team.ts, docs/docs/guide/introduction.md
closes #17
Sorry for the confusion @Ubugeeei! Let's remove the community members until I figure out what I want.
=> chore: remove community members for now

src/docs/guide/usage/linter.md, src/docs/guide/usage/parser.md, src/docs/guide/usage/resolver.md
I just refined usage pages:
- Unify sectioning
- Show instructions with Vue components
- Fix some sentences
@Boshen 
Sorry if you are working on the same pages.
Would you check the direction of this PR looks fine to you, and add more contents as needed?
If it looks good to you, I will modify the other pages in same way.
=> feat: refine usage pages

.vitepress/theme/constants/team.ts
I just fixed types.
I will merge this PR imediately.
=> chore: improve types

.github/labeler.yml, .github/workflows/ci-build-and-deploy.yml, .github/workflows/ci-pr-label.yml, .github/workflows/ci-semantic-pr.yml
=> chore(core): add ci workflows

.github/workflows/ci-build-and-deploy.yml, .textlintrc.json, package.json, pnpm-lock.yaml, src/blog/index.md, src/docs/contribute/performance.md, src/docs/guide/usage/linter.md, src/docs/learn/ecmascript/grammar.md, src/docs/learn/ecmascript/spec.md, src/docs/learn/ecosystem.md, src/ja/blog/index.md, src/ja/docs/contribute/performance.md, src/ja/docs/guide/usage/linter.md, src/ja/docs/learn/ecmascript/grammar.md, src/ja/docs/learn/ecmascript/spec.md, src/ja/docs/learn/ecosystem.md
I've made sure everything works correctly by installing and using textlint-rule-terminology.
=> feat(core): add textlint

crowdin.yml
=> chore(core): refine Crowdin config

.github/workflows/ci-cd.yml, crowdin.yml
Related to #13 and #52.
I will merge this PR immediately to check if it works as expected.
=> chore(core): refine Crowding and GitHub workflow config

src/docs/guide/introduction.md
=> docs(core): add Testimonials to introduction

.vitepress/config/shared.ts, src/index.md, src/ja/index.md, src/zh/index.md
=> docs(core): use smaller images

src/docs/learn/parser_in_rust/ast.md
=> docs(core): update ast.md

src/docs/guide/usage/resolver.md, src/ja/docs/guide/usage/resolver.md, src/zh/docs/guide/usage/resolver.md
Update the oxc_resolver crate link.
=> docs(l10n): update `oxc_resolver` crate link

.vitepress/theme/components/Banner.vue, .vitepress/theme/components/shims.d.ts, .vitepress/theme/index.ts, package.json, pnpm-lock.yaml
=> docs(core): add top banner for oxlint

.vitepress/theme/components/Banner.vue
=> docs(core): support for persist removal of banner of closing it

.typos.toml, .vitepress/config/en.ts, src/docs/learn/architecture/linter.md
@leaysgur I copied your content and chatGPTed it.
I like the overall content structure. I will clean this up and expand it in the future.
=> docs: add linter architecture

src/docs/guide/usage/linter.md
Refs: https://github.com/oxc-project/oxc/pull/3039 https://github.com/oxc-project/oxc/pull/3044
=> docs: update cli format options

.vitepress/config/index.ts, .vitepress/config/shared.ts, .vitepress/theme/components/Hero.vue
I'm not sure if it is cute or disorienting, So it is up to you to decide @Boshen. The code isn't that phenomenal but should perform relatively well.
=> feat: Hero3D?

.github/workflows/ci.yml, cli/commands/create-blog-post.ts, package.json, pnpm-lock.yaml
=> ci: add oxlint step

.vitepress/theme/constants/team.ts
=> feat: add don to the team page

src/docs/learn/architecture/test.md
Improve (in my opinion) language and fix a few typos in the testing architecture doc.
=> improve language in test infrastructure doc

src/docs/guide/projects.md
https://github.com/long-woo/stc/blob/master/src/plugins/javascript/oxc.ts#L14
=> Added `oxc-transform` to use project `stc`

.vitepress/config/en.ts, .vitepress/sidebar.blog.json, src/blog/2024-09-29-transformer-alpha.md
=> Oxc Transformer Alpha

.prettierignore, .vitepress/theme/components/Alert.vue, .vitepress/theme/components/Banner.vue, .vitepress/theme/components/Hero.vue, package.json
I also included changes created by running this script.
=> chore: add lint:fix script

src/docs/guide/projects.md
See https://github.com/oblador/sovra
=> Add sovra to Project using Oxc

.vitepress/config/en.ts, src/docs/learn/architecture/ast-tools.md
=> feat: add documentation on ast tools

src/docs/contribute/linter/adding-rules.md
reordered for simplier tracking:
https://github.com/oxc-project/oxc/blob/main/justfile#L159-L199
=> docs(linter): adding rule: update just commands according to the just file

src/docs/contribute/debugging.md
relate to this [pr](https://github.com/oxc-project/oxc/pull/8271) in oxc
=> docs(contribute): debug linter in vscode

.vitepress/config/en.ts, src/docs/contribute/codegen.md, src/docs/learn/architecture/formatter.md, src/docs/learn/architecture/introduction.md, src/docs/learn/architecture/minifier.md, src/docs/learn/architecture/resolver.md, src/docs/learn/architecture/transformer.md
Fixes #269 
- Remove blank pages
- Adjust sidebar settings
When the content is ready, we can then create another page.
=> chore(docs): Remove blank pages and update sidebar

src/docs/contribute/linter/adding-rules.md
Fix a small typo found in the doc.
=> docs: small typo fix

src/docs/guide/benchmarks.md
This PR updates the benchmark information to reflect what's written in the readme
https://github.com/oxc-project/bench-javascript-parser-written-in-rust
=> chore: update benchmark information

src/blog/2025-03-15-oxlint-beta.md
Use speedup multipliers instead of percentage decrease.
=> Update benchmark speedups

src/docs/guide/usage/linter.md
could not find any big problems anymore. Sure their is some optimization that can be done. 
But I am happy to get bug reports now and improve it little by little like the other eslint related package ;) 
related https://github.com/oxc-project/oxlint-migrate/pull/46
=> docs(linter): oxlint-migrate is ready for the world

package.json
Align the version of NodeJS in `package.json` with `.node-version`.
=> chore(deps): bump `volta.node` version in `package.json`

src/docs/guide/usage/linter/plugins.md
Since the linked issue is closed I changed the link to point to the pinned issue and added a reference to the discussion.
=> docs(linter): update custom plugin issue link

src/docs/guide/usage/linter/plugins.md
https://deploy-preview-374--oxc-project.netlify.app/docs/guide/usage/linter/plugins.html
=> fix plugins.md broken link

.vitepress/theme/index.ts, .vitepress/theme/overrides.css
=> fix: consistent avatar sizes on member page

src/docs/guide/usage/linter/type-aware.md
https://github.com/oxc-project/oxc/issues/13993#issuecomment-3341320218
=> docs: add note about auto-fixes for type-aware rules in CLI

src/docs/guide/usage/linter.md
https://github.com/oxc-project/oxc-project.github.io/pull/522#discussion_r2397654250
=> docs(linter/usage): link to `Type-Aware Linting` Section

src/docs/guide/usage/linter.md
https://github.com/oxc-project/oxc/pull/14106
=> docs(linter): remove "no node required" paragraph
